name: llama_bev
channels:
  - omgarcia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - gcc-6=6.1.0=2
  - gmp=6.1.0=1
  - isl=0.17.1=0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mpc=1.0.1=0
  - mpfr=3.1.2=0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.0=h0371630_2
  - readline=7.0=h7b6447c_5
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.5.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.3
      - black==24.8.0
      - bleach==6.1.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - clip==1.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - colorlog==6.9.0
      - comm==0.2.2
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==44.0.2
      - cycler==0.12.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - deepspeed==0.15.2
      - defusedxml==0.7.1
      - descartes==1.1.0
      - detectron2==0.6
      - distro==1.9.0
      - einops==0.8.1
      - einx==0.3.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fairscale==0.4.8
      - fastapi==0.115.11
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.14.0
      - fire==0.7.0
      - flake8==5.0.4
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozendict==2.4.6
      - fsspec==2025.3.0
      - ftfy==6.2.0
      - fvcore==0.1.5.post20221221
      - gradio==4.44.1
      - gradio-client==1.3.0
      - grpcio==1.70.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.3
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - iopath==0.1.9
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jaxtyping==0.2.19
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.9.0
      - jmespath==0.10.0
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - language-evaluation==0.1.0
      - lazy-loader==0.4
      - llvmlite==0.31.0
      - local-attention==1.10.0
      - lyft-dataset-sdk==0.0.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.5.2
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.3
      - mmcv-full==1.4.0
      - mmdet==2.14.0
      - mmdet3d==0.17.1
      - mmengine==0.10.7
      - mmsegmentation==0.14.1
      - model-index==0.1.11
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.31.0
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==2.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numba==0.48.0
      - numpy==1.19.0
      - nuscenes-devkit==1.1.10
      - nvidia-ml-py==12.570.86
      - omegaconf==2.3.0
      - openai==1.67.0
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.11
      - ordered-set==4.1.0
      - orjson==3.10.15
      - oss2==2.17.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.0.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.0.1
      - pluggy==1.5.0
      - plyfile==1.0.3
      - portalocker==3.0.0
      - prettytable==3.11.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==3.20.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pycocotools==2.0.7
      - pycodestyle==2.9.1
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyflakes==2.5.0
      - pygments==2.19.1
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - pyzmq==26.3.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rpds-py==0.20.1
      - ruff==0.11.2
      - safetensors==0.5.3
      - scikit-image==0.19.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - setuptools==60.2.0
      - shapely==1.8.5
      - shellingham==1.5.4
      - similaritymeasures==1.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.44.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.0.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==0.3.2
      - tinycss2==1.2.1
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==1.9.1+cu111
      - torchaudio==0.9.1
      - torchvision==0.10.1+cu111
      - tornado==6.4.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - typeguard==4.4.0
      - typer==0.15.2
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.2.3
      - uvicorn==0.33.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.20.2
prefix: /home/renxin/miniconda3/envs/llama_bev
